services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app-container
    restart: always
    ports:
      - 8000:8000
    networks:
      - docker-network
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres-container
    restart: always
    shm_size: 128mb
    ports:
      - 5433:5432
    volumes:
      - /db-data:/postgres/data
    environment:
      - POSTGRES_DATABASE=${DB_DATABASE}
      - POSTGRES_USERNAME=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - docker-network

volumes:
  db-data:
networks:
  docker-network:
    driver: bridge
