services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app-container
    image: bllall/hireverse
    volumes:
      - ./:/app
      - ./vendor:/app/vendor
    restart: always
    networks:
      - docker-network
    depends_on:
      - db
  nginx:
    image: nginx:stable-alpine
    ports:
      - 81:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-network
    depends_on:
      - laravel-app

  db:
    image: postgres
    container_name: postgres-container
    restart: always
    shm_size: 128mb
    ports:
      - 5433:5432
    volumes:
      - /db-data:/postgres/data
      - ./docker/postgres/postgres-hireverse-test.sql:/docker-entrypoint-initdb.d/postgres-hireverse-test.sql
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      # - POSTGRES_MULTIPLE_DATABASES=hireverse,hireverse_test
    networks:
      - docker-network

volumes:
  db-data:
networks:
  docker-network:
    driver: bridge
