services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app-container
    image: bllall/hireverse
    volumes:
      - ./:/hireverse
      - ./vendor:/hireverse/vendor
    restart: always
    networks:
      - docker-network
    depends_on:
      - db
      - redis
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/:/etc/nginx/ssl/
    networks:
      - docker-network
    depends_on:
      - laravel-app

  redis:
    image: redis:alpine
    container_name: redis-container
    restart: always
    ports:
      - 6379:6379
    networks:
      - docker-network
  db:
    image: postgres
    container_name: postgres-container
    restart: always
    s`m_size: 128mb
    ports:
      - 5433:5432
    volumes:
      - /db-data:/postgres/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - docker-network

volumes:
  db-data:
networks:
  docker-network:
    driver: bridge